### ISSUE TITLE
Not working with input fields

### ISSUE THREAD

**Issue by mithri** [b13/link2language#1]
Hi,

the extensions only works within the RTE linkhandler. With input fields the link generated is: "ID&L=1", but the typolink viewhelper expects: "ID - - - &L=1". 

If you link an image, there is no link in the frontend because of that. I didn`t find a way to fix that. Maybe you have an idea.

Tobias

**Comment by bmack** [comment]
What TYPO3 version are you running this?

**Comment by bmack** [comment]
Closing the issue due to lack of feedback
