### ISSUE TITLE
autoload fails in classmap-authoritative mode

### ISSUE THREAD

**Issue by denvis** [b13/link2language#12]
autoload fails in classmap-authoritative mode ( e.g. in deployment scenarios like surf)

Problem ist the lower l in the Namespace
`	"autoload": {
		"psr-4": {
			"B13\\Link2language\\": "Classes/"
		}
	},` 
should be
`	"autoload": {
		"psr-4": {
			"B13\\Link2Language\\": "Classes/"
		}
	},`

Also in ext_localconf.php
`\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addPageTSConfig(
    'TCEMAIN.linkHandler.page.handler = B13\\Link2language\\LinkHandler\\PageLinkHandler'
);
`
should be
`\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addPageTSConfig(
    'TCEMAIN.linkHandler.page.handler = B13\\Link2Language\\LinkHandler\\PageLinkHandler'
);
`

You can reproduce the issue with
`composer du --classmap-authoritative`

**Comment by bmack** [comment]
Hey @denvis ,

thanks for the info. can you provide a Pull request?

**Comment by bmack** [comment]
Merged
