### ISSUE TITLE
Can you release a version with v11 support (please)?

### ISSUE THREAD

**Issue by sypets** [b13/link2language#16]
The latest release is [2.0.0](https://github.com/b13/link2language/tree/2.0.0)  (from Jul 19, 2021).

The lastest "master" already supports v11:

* composer: https://github.com/b13/link2language/blob/master/composer.json
* ext_emconf.php: https://github.com/b13/link2language/blob/master/ext_emconf.php

I am interested in this extension for v11. If it is helpful, I can also test it on v11.

**Comment by bmack** [comment]
done. https://extensions.typo3.org/extension/link2language
