### ISSUE TITLE
No link rendered if "Hide default translation of page" is set

### ISSUE THREAD

**Issue by lorenzulrich** [b13/link2language#3]
If a link is set to a page with "Hide default translation of page" set, the link is not rendered at all.

**Comment by mindpilot** [comment]
introduced in v8.7.17 by https://review.typo3.org/c/Packages/TYPO3.CMS/+/57345/2/typo3/sysext/frontend/Classes/Typolink/PageLinkBuilder.php

**Comment by achimfritz** [comment]
works for me in v12, i think this issue is outdated

**Comment by lorenzulrich** [comment]
I can confirm that we currently use an unpatched core/link2language, so that seems to be correct.
